[package]
name = "guessing_game"
version = "0.1.0"
authors = ["ALRW <awerner1@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

[net]
git-fetch-with-cli = true
